# Generated by Django 5.0.3 on 2024-03-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('chatapp', '0005_profile_alter_friend_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
